[package]
name = "sqlight"
version = "1.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
crossterm = "0.29"
native-tls = "0.2.18"
postgres = "0.19.14"
postgres-native-tls = "0.5.3"
ratatui = "0.30.2"
rpassword = "7.5.4"
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["preserve_order"] }
unicode-width = "0.2"
